### ISSUE TITLE
Autogeneration of absolute paths in settings/system_paths.csv means .talon/user is not portable across machines

### ISSUE THREAD

**Issue by rntz** [talonhub/community#1036]
system_paths.csv gets autogenerated on talon startup and contains absolute paths to various locations including in the user's home directory. This means it's impossible to reuse your talon configuration across different machines, especially on different OSes, _even if you haven't customized anything_. I just got bitten by this by saying `go talon user` in a terminal and having it try to cd to a nonexistent directory. 

It would be good if folks could (with proper care) reuse their talon config across different machines & OSes. I'm not sure what the right solution here is - probably to allow paths starting with `~` to refer to the home directory? I think that would at least be an improvement. However, some of these paths are generated by talon actions, eg `actions.path.talon_user()`, which generate absolute paths. So that makes that awkward.

**Comment by DonnerWolfBach** [comment]
I can say to this that the tilde "~" works for Powershell **but not **for the older cmd on windows.

**Comment by knausj85** [comment]
Worst case, it might make sense for this particular file to be generated in a host-specific manner via scope.get("hostname")

**Comment by DonnerWolfBach** [comment]
Also a two things were linux and windows would bite each other:
1. Windows does mount other partitions under D:/, E:/ etc. In Linux you can mount that everywhere - but the path will be different, so no way to make this for work for this case
2. The talon directory in linux is under ~/.talon. in windows it's under ~/appdata/roaming/talon. So this would also not work (easily)
