### ISSUE TITLE
Change VSCode "format that" to "file format"

### ISSUE THREAD

**Issue by maxbruening** [talonhub/community#1176]
I believe this is better because it is more object oriented. Moreover, "that" usually refers to this thing that was done last, for example the last utterance

**Comment by auscompgeek** [comment]
For posterity, it's these commands:

https://github.com/knausj85/knausj_talon/blob/2e9e03ddb559c782e65650120a9d91079b6dc643/apps/vscode/vscode.talon#L106-L107

We should also figure out what to do about this JetBrains command:

https://github.com/knausj85/knausj_talon/blob/2e9e03ddb559c782e65650120a9d91079b6dc643/apps/jetbrains/jetbrains.talon#L37
