### ISSUE TITLE
`customize` command does not work on Windows 11

### ISSUE THREAD

**Issue by jmegner** [talonhub/community#1228]
On my Windows 11 computer, the command "customize websites" tries to launch Notepad on a nonexistent file and Notepad gives this error message:

```
Notepad
Cannot find the C:
Sb2FtaW5nXHRhbG9uXHVzZXJcdGFsb24tY29uZmlnLWptZVxzZXROaW5nc1x3ZW
JzaXRlcy5jc3YAAAEBAAAAAYCCAuQCAAAAAAAA.txt file.
Do you want to create a new file?
```

Similar problem for other commands like "customize additional words".  Nicholas Riley says the customize commands work on Windows 10. (Update: works on my Windows 10 work computer as well.)

If I run `import os; os.startfile(r"C:\Users\jmegn\AppData\Roaming\talon\user\talon-config-jme\settings\websites.csv", "edit")` (the path is correct) in the REPL, I get the same error.

**Comment by AndreasArvidsson** [comment]
I tried `os.startfile(path, "edit")` on windows 11 and it works fine for me. Opens with notepad. 
Do you have the same problem if you try to open another text file? Preferably a file you just created to make sure this isn't a permission problem.

**Comment by jmegner** [comment]
Just tried again on my Windows 11 computer that had the problem earlier, and it worked (launched notepad on the websites.csv when I said "customize websites").  My best guess is that my earlier version of Windows 11 didn't play nice with what the customize command was doing.

I'll close this.
