### ISSUE TITLE
Dragging broken in macOS without an eye tracker

### ISSUE THREAD

**Issue by brief** [talonhub/community#1241]
The drag command doesn't work for me on Ventura (13.5 or any previous version). I can't select text or move windows or drag files. It just single clicks. Notably, I am not using an eye tracker.

This is not a new issue. I'm still new to Talon and `drag` has never worked for me (in the public or beta), so I always just assumed it required an eye tracker. Mispronounced something in Google Sheets today and it worked, undoubtedly because  they have custom mouse handling, but I couldn't get it to activate anywhere else. Found issue #974, tried the code, and it now works everywhere.

Per @lunixbochs's suggestion, I've updated things to register the tap on `mouse_drag()` and unregister things on `mouse_drag_end()`. Happy to submit a pull request if others can replicate the issue and there's no better way of fixing this.

**Comment by lunixbochs** [comment]
An event tap in python introduces input lag and stutters, so I don't want the community repo to merge this for everyone. I can likely build a native workaround that doesn't add lag due to taking the GIL.

**Comment by brief** [comment]
That would be a much better solution. Thank you!
