### ISSUE TITLE
Convert settings in `.talon` files to using literal `bool`s

### ISSUE THREAD

**Issue by phillco** [talonhub/community#1296]
Talon 0.4 shipped on July 24, 2023 which supports boolean literals in Talon files. So you can write:

```talon
user.mode_indicator_show = false
```

...instead of

```talon
user.mode_indicator_show = 0
```

This is easier to parse and also visually distinguishes boolean settings from numerical ones.

~~We might want to hold off for some amount of time (not sure what the SLA is on community supporting older public Talon versions) if people are using <=0.3, so filing this as a tracking ticket.~~

Per @lunixbochs, we don't need to support old public Talon versions, so it's safe to use boolean literals in new functionality. This ticket will track the rewriting of existing literals.

**Comment by lunixbochs** [comment]
I think if you're not going to update Talon you should also not update community or your plugins. Don't worry about supporting older Talon versions in your scripts.

**Comment by phillco** [comment]
Cool, so confirming:

- it's safe to use booleans in new functionality (as well as other new public Talon functionality going forward; we don't have to try to support old public versions)
- we can keep this ticket open for tracking the rewriting of existing numerical setting literals to booleans (probably not a huge rush, this will create a lot of merge conflicts for people who have changed those settings)
