### ISSUE TITLE
Add support for a snippet directory not inside of the community folders

### ISSUE THREAD

**Issue by AndrewDant** [talonhub/community#1306]
I would like to be able to define snippet files somewhere other than the community repo and use them with the new snippet feature, for example to allow defining a set of snippets in a private repository to keep proprietary code in snippets private while still backed up by git. Most likely this would be implemented as a setting which can contain a path for the snippet file watcher to look at in addition to the default.

**Comment by AndrewDant** [comment]
@AndreasArvidsson

**Comment by AndreasArvidsson** [comment]
I've now added a pull request, but I don't really have the time at the moment to fully test it out. Could you give this one a spin? #1312

**Comment by pokey** [comment]
I believe this was fixed in #1312
