### ISSUE TITLE
Add support for - in snippet bodies

### ISSUE THREAD

**Issue by fidgetingbits** [talonhub/community#1310]
I was trying to add a snippet for generating snippets, such as:

```
language: snippet
---

name: snippetDeclaration
phrase: snippet
insertionScope: statement
-
name: $0
phrase:
insertionScope:
-
---
```

This runs into a parser error from `snippet_parser.py:parse_document()`: 
```
2023-11-10 10:34:06.115    IO ERROR | snippet.snippet:3 | Found multiple '-' in snippet document '
```

I tried to do some naive escaping (`\-`) but that didn't work. I don't have time at the moment to fix it properly or check if there's some other way to escape, so filing.

**Comment by pokey** [comment]
https://github.com/talonhub/community/pull/1302#discussion_r1378897209
