### ISSUE TITLE
How to use this zoom mouse??

### ISSUE THREAD

**Issue by openSourcerer9000** [talonhub/community#1340]
Hi, I'm new to talon and came just for this feature: 
https://www.youtube.com/watch?v=VMNsU7rrjRI

1:
how do I get the mouse to zoom in like that to do precise clicks? It doesn't have any documentation in the demo. I've tried commands "control mouse" and "zoom mouse" but I'm not noticing a difference. I don't have an eye tracker, so I built a python service that uses ML to infer a mouse point from your head position from your webcam (can post that below when it's finished if anyone's interested). So the { `pop` -> zooms in -> `pop` -> clicks } feature is the only thing I need to set up.

2:
How to get the pop sound to work? I tried adding this file to `/user` one directory above `/user/community`. I have perfect pop precision, but I cannot get it to register that noise. The mic picks it up fine, other commands work, but that one never does.

```from talon import Module, actions

mod = Module()

@mod.action_class
class Actions:
    def noise_trigger_pop():
        """Called when a pop noise is detected, clicks the left mouse button"""
        actions.mouse_click(button=0)```

**Comment by openSourcerer9000** [comment]
Thinking about it, the whole zoom mouse thing may be hardcoded for using an eye tracker inside talon to move the cursor, since it looks like it's using a virtual cursor for the zoom part for some reason.

If that's the case, could it be possible to pipe my realtime x,y output to talon, rather than to control the mouse directly? With all my dependencies, I'm dubious that the two python envs could be compatible.

**Comment by lunixbochs** [comment]
if you just want to zoom the desktop in, there are features for that on both windows and macos

**Comment by knausj85** [comment]
The zoom mouse functionality is native to talon, and presently requires an eye tracker. It can be enabled via the specified voice commands or the talon context menu when a supported eye tracker is connected. 

As such, I'm going close this one out.
