### ISSUE TITLE
Help UI is too small

### ISSUE THREAD

**Issue by Julhol-droid** [talonhub/community#1358]
When opening help center f.e. help alphabet the UI is really small.
Is there a way to make it bigger.

Thanks in advance.

![image](https://github.com/talonhub/community/assets/79325648/8e65669c-30f6-4d88-a459-02f3c5f8acc6)

**Comment by nriley** [comment]
In general you can set [imgui.scale in settings.talon](https://github.com/talonhub/community/blob/main/settings.talon#L3) but it looks like this may be an issue with your display's DPI/scale factor (whatever is appropriate for the OS you are using, which you don't mention although it doesn't look like macOS). Would recommend discussing on the Talon Slack as this is a core Talon issue not a community one.
