### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by jaresty** [talonhub/community#1406]
I'm having to do Kotlin lately. I would really appreciate if community could add support for the Kotlin language. There is some existing work in one of the community forks [here](https://github.com/okonomichiyaki/knausj_talon/blob/06ebde9f11e8738f5f82a7c2ff419541f068d769/lang/kotlin/kotlin.py)

**Comment by auscompgeek** [comment]
Was enough support for Kotlin added in #1408 for this to be considered done, or did you have more in mind @jaresty?

**Comment by jaresty** [comment]
Good question. I've got an open PR to add spacing on keywords. I'd like to get that merged and then I can close this issue.
