### ISSUE TITLE
Change text editing grammar to be more generic

### ISSUE THREAD

**Issue by pokey** [talonhub/community#1412]
# The problem

We have a large set of commands in community that consist of a (partial) cross product of "actions" with "modifiers" (to use Cursorless terminology): {select, copy, cut, delete, etc} x {word, line, file, etc}. For example, "select line", "select word", "select file", "copy word", etc. Because the commands in this cross product are just defined one by one, we can end up with inconsistency, as well as difficulty changing things.

In addition, it's more difficult for users to customize the spoken forms for these actions. Eg they may want to change `"select"` to `"take"`. Today, that would require forking and changing many lines in their `.talon` files.

Another problem is that the user doesn't have consistency between their global editing grammar and Cursorless, which leads to cognitive dissonance for users that use Cursorless. Beyond Cursorless, other grammars may want to leverage similar actions. For example @rokubop is working on a grammar for sophisticated actions based on a grid for use in gaming / drawing. This grammar would have actions such as `"copy"`, `"select"`, etc

# The solution

We propose to create the following

- a list for actions such as `"copy"`", `"select"`, etc. This list would be defined using a `.talon-list`
- a list for "modifiers" such as `"word"`", `"line"`, `"file"`, etc, also as a `.talon-list`
- a rule `<user.action> <user.modifier>` that would first run the modifier, then the action. For example, the user could say `"copy line"`, and that would first call `actions.edit.select_line()`, then call `actions.edit.copy()`
- In Cursorless, we could leverage these lists, and use the `user.cursorless` tag to override the Talon action that implements the above rule to instead run the command using Cursorless

To make things easier, we actually have a lot of the code to make this work already written in Cursorless. We use this code to implement a set of fallback actions that make it so that if you issue Cursorless commands when your focus is in a text box in VSCode, rather than in the main editor area, it will fallback to using Talon actions. For example, just as described above, if you say `"copy line"`, it will first call `actions.edit.select_line()`, then call `actions.edit.copy()`. See [here](https://github.com/cursorless-dev/cursorless/blob/main/cursorless-talon/src/fallback.py) for the implementation. 

The way we've implemented it is that the Cursorless talon grammar sends the usual json payload to Cursorless, and if Cursorless detects that your focus is in a text box, it will do nothing, but instead return a json payload describing what fallback actions Talon should perform.

We could adopt a somewhat similar (but simpler) approach universally. Instead of sending a json payload to Cursorless and waiting for the response, we would define a spoken grammar, as described above, for the subset of actions / "modifiers" that are supported everywhere, and these captures would directly run the desired Talon actions. Note that we could then remove some of the definitions from Cursorless's fallback and just use the version built into community

Credit for this idea, as well as for the fallback code, goes primarily to @AndreasArvidsson

**Comment by maxbruening** [comment]
I guess this would also simplify porting to other languages.
