### ISSUE TITLE
New user defined modes automatically contain mode switching commands in contradiction to the talon wiki

### ISSUE THREAD

**Issue by maxbruening** [talonhub/community#1437]
When a user defines a new mode, this mode automatically contains mode switching commands like "command mode" or "sleep all".  This is due to the headers of the files [modes_not_dragon.talon](https://github.com/talonhub/community/blob/main/core/modes/modes_not_dragon.talon) and [modes.talon](https://github.com/talonhub/community/blob/main/core/modes/modes.talon).  

According to the [talon wiki](https://talon.wiki/Customization/Talon%20Framework/modes) this behaviour runs against the primary purpose of a new user defined mode: "So why might you add a custom mode? The main reason is because you want to disable all normal voice commands so only the ones in your mode are active. An example might be where you were using a full screen computer game, and wanted to eliminate potential conflicts with commands outside the game context."

So I guess either the wiki or community should change. 

Personally, I think community should change. I stumbled across this because I wanted to have a new empty mode so that I could use different voice software in combination with Talon (i.e. voice from the other software but Talon noises).

**Comment by maxbruening** [comment]
Maybe the mode switching commands should be the first thing to appear in every mode's talon file? This would make things very explicit and be in the spirit of #1122 . 

If we want users to receive warnings about already being in a mode (#1327) this would also need to be explicitly defined in every mode's talon file.

I would argue it is not necessary to be able to switch to e.g. command/dictation/sleep mode via pre-defined voice commands when one creates a new mode. If I want that, I need to write it explicitly.

Drawback: Slightly more lines of code, especially the more modes there are.
Benefit: No unexpected commands in new modes. We do not expect users to have many modes.

**Comment by AndreasArvidsson** [comment]
I agree with you. If you make a custom mode that should be empty by default.
