### ISSUE TITLE
Question: How to dictate in Spanish?

### ISSUE THREAD

**Issue by openSourcerer9000** [talonhub/community#1494]
How can I change the language of the Conformer D 2023 model on PC? Or how can I import a different model that supports spanish? It seems it's locked to work with specific models, rather than anything I grab off hugging face. 

This is the only documentation I can find on how one might do this; however, adding `language: es_CO` to the top of the settings.talon file does nothing.
```
0.3.0 (Jul 7, 2022)
Breaking changes:

from __future__ import annotations does not work with runtime type checking. Talon now throws an error when you import annotations.
Remove m._words[...] attribute in captures. You should just index m[...] directly.
Language support: commands, lists, and captures are now implicitly scoped to en_US (English US). They will not be available in other languages by default. You should reimplement them for your specific language, e.g. to match German, use:
language: de_DE at the top of a .talon file.
ctx.matches = 'language: de_DE' in Python.
```

If there's a better forum for a question, please direct me to it, thanks.

**Comment by AndreasArvidsson** [comment]
Questions like this is probably best to ask on slack: https://talonvoice.slack.com
The answer is that conformer is english only at the moment. If you have the Talon beta you can install google web speech as a secondary engine. 
There are example code how to set that up here:
https://github.com/talonvoice/webspeech_examples
