### ISSUE TITLE
Copy block command conflicts with cursorless

### ISSUE THREAD

**Issue by jaresty** [talonhub/community#1495]
Some new commands were introduced to community recently that conflict with the cursorless copy block command. This conflict is unfortunate because there is no simple way to fix this without editing this repository.

Related to this issue as well : https://github.com/cursorless-dev/cursorless/issues/428

**Comment by fidgetingbits** [comment]
Also relevant I think: https://github.com/talonhub/community/issues/1412

Probably implementing the actions proposed by #1412 will fix a lot of these problems. I think it will also improve the fallback functionality in cursorless

**Comment by AndreasArvidsson** [comment]
https://github.com/talonhub/community/pull/1498
One this had merged you can just with a tall long list file change enable or disable spoken forms without changing community.

**Comment by AndreasArvidsson** [comment]
Fixed with #https://github.com/talonhub/community/pull/1498

**Comment by jaresty** [comment]
Thank you!

**Comment by jaresty** [comment]
is this fixed on the cursorless side too? I still seem to be running into a conflict

**Comment by AndreasArvidsson** [comment]
There is no planned change in cursorless.
You need to use a different spoken forms in community and cursorless. Or make sure not both are enabled at thr damer time.

**Comment by jaresty** [comment]
Oh-I thought there was a plan for cursorless to override the same command name. If there isn't a plan to change cursorless, doesn't that mean that the default configuration is still a conflict? (I.e. copy is the same?)

**Comment by AndreasArvidsson** [comment]
That is a potential future use, but not something needed to solve the conflicts now.
I changed the default in community to paragraph so the conflict is gone.

**Comment by jaresty** [comment]
ah! I see.  yes, that is indeed fixed.  Thank you!
