### ISSUE TITLE
This should use the new command names talon list

### ISSUE THREAD

**Issue by jaresty** [talonhub/community#1516]
https://github.com/talonhub/community/blob/676a3043e9d8a7ed4e5ce3764a7e21b5514084dd/tags/line_commands/line_commands.talon#L37

**Comment by jaresty** [comment]
Implemented in https://github.com/talonhub/community/pull/1498

**Comment by nriley** [comment]
From the community backlog session — this would not be easy to add to the existing implementation as it is implementing `edit_commands` which are global versus this command being gated behind the user.line_commands tag. In addition there are no existing compound edit commands that take arguments like a line number.

**Comment by jaresty** [comment]
My primary concern here was trying to find a way to alias the 'select' command so it behaves the same in cursorless and community. I wanted to use 'take' everywhere but that's not really possible at present anyway. If it ever became possible to use the same verb and cursorless and community for select, this command being an outlier would be more frustrating but for now I don't think it really matters that much. I'll close this issue for now.
