### ISSUE TITLE
WARNING [emacs] `user.cut_line` skipped due to no matching declaration

### ISSUE THREAD

**Issue by chdoc** [talonhub/community#1522]
I am suddenly seeing the following warning every time I focus Emacs (latest talon beta and community) :
```
2024-07-31 22:13:18.304 WARNING actions skipped because they have no matching declaration:
    Context(user.community.apps.emacs.emacs): user.cut_line
```
Presumably this is due to there not being any context or tag that actually declares this function. Indeed, code search suggests the function is unused. Maybe this can simply be removed?

**Comment by fidgetingbits** [comment]
@AndreasArvidsson your recent https://github.com/talonhub/community/commit/28c12812c325646a981497314e9971351f25f88b triggered this in emacs and looks like will affect readline.py too. Haven't looked at your commit in detail yet as I havent merged it into my own repo, but presumably there is something those old actions can be swapped out with?

Possibly another thing to consider breaking change file update for.

**Comment by AndreasArvidsson** [comment]
Sorry we missed that one. I now have a pr to fix this.
https://github.com/talonhub/community/pull/1523
