### ISSUE TITLE
Add a please action for use in command palettes and the like

### ISSUE THREAD

**Issue by nriley** [talonhub/community#1536]
This voice command is defined in many places in community already, and with changes like #1534 these implementations can drift from one another.

**Comment by jaresty** [comment]
I'm suspicious that there may be some valid reasons to diverge (if the please behavior is to automatically trigger, chaining might be possible). But just to understand clearly, what is the ask here?

**Comment by nriley** [comment]
Either change all the please implementations to anchor, or implement please once with an action overridden in each app's context.

**Comment by jaresty** [comment]
I can do that. I was trying to target my original fix to just where I was feeling pain since I'm not sure how it will impact others (since I'm not using please elsewhere). I'll update the PR to accommodate this additional requirement.
