### ISSUE TITLE
Custom subtitles steal focus from talon debug window

### ISSUE THREAD

**Issue by knausj85** [talonhub/community#1552]
Version: 0.4.0-386-g7246, Branch: beta, OS: macOS-14.6.1-x86_64-i386-64bit

When attempting to use the talon debug window even with very basic commands, the custom subtitles (https://github.com/talonhub/community/tree/main/plugin/subtitles) steal focus. 

A temporary workaround is to disable subtitles in talon_debug_window/talon_debug_window.talon. I'm not sure if this is a talon bug or a custom subtitle bug

**Comment by lunixbochs** [comment]
do talon's subtitles steal focus?

**Comment by knausj85** [comment]
> do talon's subtitles steal focus?

It appears so. This appears to be Mac specific (can't speak to Linux)

**Comment by lunixbochs** [comment]
maybe winit is calling something like makeKeyAndOrderFront when we create a canvas

**Comment by lunixbochs** [comment]
I think this is fixed in beta 389

**Comment by knausj85** [comment]
Verified fixed in Version: 0.4.0-389-g05a6, Branch: beta, OS: macOS-14.6.1-x86_64-i386-64bit
