### ISSUE TITLE
core/navigation MacActions go_back() and go_forward() commands inconsistent with macOS 

### ISSUE THREAD

**Issue by cocona20xx** [talonhub/community#1563]
Not sure if this is intended or not, but according to macOS itself, the default "(go) back" and "(go) forward" command bindings are `cmd-[` and `cmd-]` respectively; `core/nagivation.py` instead defines the `go_back()` and `go_forward()` functions as `cmd-]` and `cmd-[` by default, respectively. This means that speaking "go forward" will run the command defined by the OS as go back (and vise-versa for go back running go forward), which is rather unintuitive.

**Comment by david-tejada** [comment]
That's probably not intended. They are properly bound in Safari. https://github.com/talonhub/community/blob/d426076bf746cfa6a8ab77bd89f69d5037d51a14/tags/browser/browser_mac.py#L68-L72
