### ISSUE TITLE
code formatters should use words rather than symbols

### ISSUE THREAD

**Issue by chdoc** [talonhub/community#1575]
I recently noticed that saying "smash one plus" produces "one+" and "hammer one plus" produces "One+". These being code formatters, the expected output should probably be "oneplus" or "OnePlus", i.e. exclusively contain words.

Side note: even phrase formatters only replace punctuation symbols and not other mathematical symbols.

CC: @nriley

**Comment by AndreasArvidsson** [comment]
I think we should probably add a capture `<user.text_code>` or  `<user.text_code_identifier>` that is just `<user.text>` with additional punctuation `.` and `_`. We can then use this capture for both code formatters and also other commands.
