### ISSUE TITLE
Migrate language definitions to `code_languages.py`

### ISSUE THREAD

**Issue by nriley** [talonhub/community#1585]
From https://github.com/talonhub/community/pull/1528#issuecomment-2336158817:

> In the community session today we talked further on this topic. We think we should probably have a new python file `code_languages.py` where we have the language definitions. This python file can then be used by the language modes and the snippets. 
> 
> We want to have these language definitions typed and something like this could probably work: 
> ```py
> string_or_list = str | list[str]
> lang = tuple[str, string_or_list] | tuple[str, string_or_list, string_or_list]
> 
> languages: list[lang] = [
>     ("python", ["python"]),
>     ("java", "java"),
>     ("javascript", ["javascript"], ["something something"]),
> ]
> ```
>

**Comment by AndreasArvidsson** [comment]
I wonder if we're trying to be to clever here. May be just a simple data class with fixed types would be simpler and better for readability?

phttps://github.com/AndreasArvidsson/andreas-talon/blob/34bdbb8e8bcbf6b190d87099449dc8832f98f1cd/core/languages/languages.py#L6-L44

**Comment by knausj85** [comment]
I personally think a data class would be cleaner.
