### ISSUE TITLE
Where do I find Jetbrains IDE RPC ports?

### ISSUE THREAD

**Issue by qubitz** [talonhub/community#1598]
I'm attempting to add support for a new jetbrains IDE (RustRover) and can't for the life of me find where everyone is pulling [these port numbers](https://github.com/talonhub/community/blob/899e5844104232a620fad62797cdfc6a9a58e2b5/apps/jetbrains/jetbrains.py#L15) from. I see knausj85 and some others adding them in the blame, but I can't find any documentation, internally within talon or externally with google. The closest I could come was the open source for [intellj-community](https://github.com/JetBrains/intellij-community).

Were can I find the port numbers for the various jetbrain IDEs?

**Comment by lunixbochs** [comment]
https://github.com/anonfunc/intellij-voicecode/blob/master/src/main/java/com/github/anonfunc/vcidea/VoicecodePlugin.java#L28

**Comment by qubitz** [comment]
Amazing detective work! It seems unfortunately, RustRover is not included. I'll make an issue over there and 🙏. Also realizing I should have asked this as a discussion. Thanks @lunixbochs!
