### ISSUE TITLE
Address why `mouse_continuous_scroll_amount` setting is divided by 10

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonhub/community#1605]
https://github.com/talonhub/community/blob/4c0b2ba9ae13ae28b32b44691e7079d6bb92b015/plugin/mouse/mouse_scroll.py#L187

**Comment by AndreasArvidsson** [comment]
Should be as to remove `/ 10`? Users who have changed this setting of course need to change it again if we do that.

**Comment by nriley** [comment]
On the community backlog session we agreed that it does not make sense to include an arbitrary divider here. This setting is already specific to the continuous scroll amount. We should make sure when we pick a new default (or perhaps a platform specific default) that it scrolls approximately the same amount across platforms — potentially adding `settings_mac.talon`, etc.
