### ISSUE TITLE
[FR] Command to swap between multiple open windows from the same app

### ISSUE THREAD

**Issue by xavier630** [talonhub/community#456]
For example, I often have multiple Google Chrome windows open as separate spaces. The command "focus chrome" will open one of the windows, but I am missing a way to switch between them to the other one. 

Coming from a Mac perspective but there is likely a similar problem for windows users

Please let me know if there is indeed a way to do this and I just don't know it (I've had no luck with commands like window next)

**Comment by lunixbochs** [comment]
On Mac does command back tick work for you?

**Comment by xavier630** [comment]
As far as I can tell, this doesn't work if your windows are using Mac 'Spaces', only if they part of to a desktop.

Also, arguably, there should be a first-class toggle even if that did work like the 'focus app' command.

**Comment by ym-han** [comment]
Might be able to get what you want by using Contexts (https://contexts.co/) and adding voice bindings to keyboard shortcuts defined in Contexts. I just started using Contexts myself, and have been finding it pretty nice.

**Comment by astropuffin** [comment]
This works perfectly on Mac with `window next` but not at all on Windows. I wrote a `focus` command (see https://github.com/knausj85/knausj_talon/pull/443) but that only works for windows. I have no idea how to make a unified voice interface for this, as the different OSs seem to function very differently.

**Comment by knausj85** [comment]
I presently use Easy Window Switcher for this functionality on Windows.

**Comment by xavier630** [comment]
Just to be clear @astropuffin, `window next` does not work on mac with ['spaces'](https://support.apple.com/en-gb/guide/mac-help/mh14112/mac) as far as I can tell

**Comment by xavier630** [comment]
And that focus command you made for windows looks potentially pretty useful

**Comment by xavier630** [comment]
For now, I can probably put all apps into desktops and stop using spaces, but it would be awesome if `window next` could swap to windows in spaces. I think that from Mac perspective, that would solve this FR

**Comment by lunixbochs** [comment]
You might be able to loop through `ui.active_app().windows()` in some meaningful way and focus specific ones.

**Comment by xavier630** [comment]
I'll close this since the work around of not using Spaces works and open a separate issue on Talon itself that window next doesn't work on Mac Spaces

**Comment by xavier630** [comment]
https://github.com/talonvoice/talon/issues/341

**Comment by lunixbochs** [comment]
Reopening, as it's up to knausj_talon to do something more specific than press cmd-` if it wants different behavior here.

**Comment by pokey** [comment]
Might be nice to use #470 once it's merged to allow focusing windows by name

**Comment by xavier630** [comment]
> You might be able to loop through ui.active_app().windows() in some meaningful way and call focus() on specific ones.

I just tested this and it looks like any apps made fullscreen as spaces don't show up in the call to `ui.active_app().windows()`.

On a side note, `ui.active_app().windows()` seems to include extra "windows" with no descriptions for each extra tab open in Chrome windows it seems.

**Comment by xavier630** [comment]
`ui.active_app().windows()` seems to include extra "windows" with no titles (maybe leftover somehow from closed windows). I restarted Chrome and they went away

**Comment by knausj85** [comment]
Addressed by https://github.com/talonhub/community/pull/1271
