### ISSUE TITLE
replace user.find with edit.find

### ISSUE THREAD

**Issue by rntz** [talonhub/community#594]
It seems like the `user.find` action defined in `code/find_and_replace.py` is redundant with the builtin `edit.find` command, except the text argument to `edit.find` is optional. We should replace uses & implementations of `user.find` with `edit.find` and upgrade implementations to default their argument to `None` and handle a `None` argument.

There may be related actions in `find_and_replace.py` that we can eliminate as well.

**Comment by rntz** [comment]
need to fix implementation of edit.find on mac to handle the text argument https://github.com/knausj85/knausj_talon/blob/e6c863a4356978652b835d88581c04d38a701096/code/platforms/mac/edit.py#L68

aegis mentions on slack: “btw on mac we can actually set the find pasteboard, with clip.set_text('text', mode='find')”

**Comment by nriley** [comment]
Just ran into this.

`user.find_next` and `user.find_previous` appear to also be affected.

**Comment by wenkokke** [comment]
> aegis mentions on slack: “btw on mac we can actually set the find pasteboard, with clip.set_text('text', mode='find')”

Just run into this as well, and it does not appear to have been patched?

If we deprecate user.find, user.find_next, and user.find_previous, then what should happen to be more complex finding commands that are defined in the find_and_replaceb

**Comment by auscompgeek** [comment]
The Mac implementation ignoring the text was fixed in #1226. All that's left is to deprecate these find actions.

**Comment by knausj85** [comment]
Completed by https://github.com/talonhub/community/pull/1499
