### ISSUE TITLE
Revisit use of modes

### ISSUE THREAD

**Issue by pokey** [talonhub/community#603]
### The problem

We have had issues in the past where commands are unexpectedly active in sleep mode, eg #561.  The problem is that if you put `mode: ` in a `.talon` file header, you disable the implicit `mode: command`, which in turn allows you to enable the file during sleep accidentally.

A quick [search](https://github.com/search?q=%22mode%3A+%22+repo%3Aknausj85%2Fknausj_talon+extension%3Atalon&type=Code&ref=advsearch&l=&l=) reveals that we _still_ have some commands active in sleep mode for this reason.  See eg [go.talon](https://github.com/knausj85/knausj_talon/blob/master/lang/go.talon#L1-L3), which results in `go` commands being active if talon is sleeping while you have a `go` file open.

### The solution

We may want to prefer using tags in many of the places that we use modes today.  For example, the following modes are good candidates to become tags:

- [x] `user.homophones`
- [x] `user.windbg`
- [x] `user.help`
- [x] `user.help_scope`
- [x] all programming language modes
- [ ] [admin ](https://github.com/knausj85/knausj_talon/blob/93e57d041ee9097e5a58a957cc6d30a94c161464/core/modes/modes.py#L6)
- [ ] debug
- [ ] ida

On the other hand, things like "game" or "solo" would be examples of good, general modes, because a mode should ideally be very transformative of the command set and make sense when enabled by itself.

**Comment by AndreasArvidsson** [comment]
I've just replaced all of my language modes with tags instead

```
mode: command
and mode: user.java

mode: command
and mode: user.auto_lang
and code.language: java
```

Turns into
```
tag: user.java

tag: user.auto_lang
and code.language: java
```

The optimal solution is of course to revaluate code.language but until then I think that tags is the cleaner solution.

**Comment by AndreasArvidsson** [comment]
@pokey @knausj85 
I've created a solution where we are back to a single line header for each language. This time using a tag.
```
tag: user.typescript
-
```
https://github.com/AndreasArvidsson/andreas-talon/blob/master/langs/javascript/typescript.talon
https://github.com/AndreasArvidsson/andreas-talon/blob/master/misc/language_mode/language_mode.py

**Comment by AndreasArvidsson** [comment]
I have now made a pr to update the programming languages to use tags instead
#776
