### ISSUE TITLE
Capitalize formatter does not capitalze first word if there is leading whitespace in selection.

### ISSUE THREAD

**Issue by tararoys** [talonhub/community#616]
In dictation mode, I try to use the following set of commands: 
```
the quick brown fox jumped over the lazy dog
select that
format selection capitalize
```

in most cases dictation mode inserts a leading whitespace in front of the quick brown fox jumped over the lazy dog, and when I try to correct that with format selection capitalize, the leading whitespace prevents the first word from being capitalized.

**Comment by splondike** [comment]
Retest after #696

**Comment by wolfmanstout** [comment]
Re #696: as described here it wouldn't be fixed because this is a shortcoming of the capitalize formatter (which I think is worth fixing separately). However,  my PR does add a new "cap that" command which correctly handles this and is easier to use than the command sequence described here.
