### ISSUE TITLE
Problem in  def _drag_window_mac(win=None): function 

### ISSUE THREAD

**Issue by atacan** [talonhub/community#618]
the function is in the file `knausj_talon/apps/platforms/mac/desktops.py`
it is called from the following talon command
`window move desk left: user.window_move_desktop_left() `
this gives
```
> user.window_move_desktop_left()
TypeError: 'Rect' object is not subscriptable
```
error

**Comment by davidsgrogan** [comment]
I think this was fixed in https://github.com/talonhub/community/pull/1054
