### ISSUE TITLE
snap screen <number> on windows 11 number doesn't match system display

### ISSUE THREAD

**Issue by somanythings** [talonhub/community#705]
when I use snap screen one, the window moves to the second screen, and vice versa.

**Comment by pokey** [comment]
So the numbers that talon uses for screens don't match the ones that windows uses. We should keep this issue open to track making it so that they do match. For now you can use the "screen numbers" command in order to see what numbers talon is using for your screen

**Comment by AndreasArvidsson** [comment]
Related issue
https://github.com/talonhub/community/issues/841

**Comment by AndreasArvidsson** [comment]
The pull request to rely on talon's screen ordering have merged. I'm gonna close this for now; if the ordering in Talon and the operating system doesn't match that sounds like a issue or bug report for Talon, not community.
