### ISSUE TITLE
Look into simplifying formatters

### ISSUE THREAD

**Issue by rntz** [talonhub/community#768]
The current formatter code is kind of yucky, and has several minor faults:

1. Formatter immune stuff doesn't play nicely with history - it invokes format_phrase multiple times instead of just once, creating multiple history entries.
2. The way formatters are represented is just kinda ugly.
3. Unformatting doesn't handle snake_case.

Andreas Arvidsson completely rewrote them (https://github.com/AndreasArvidsson/andreas-talon/blob/master/text/text.talon, https://github.com/AndreasArvidsson/andreas-talon/blob/master/text/formatters.py). Perhaps something along those lines would be better?

**Comment by rntz** [comment]
Some concerns about formatter behaviour that are relevant: #539 #674 #616 #539

**Comment by knausj85** [comment]
Addressed by https://github.com/talonhub/community/pull/1431
