### ISSUE TITLE
[Feature Request] Negative Numbers with the word "negative"

### ISSUE THREAD

**Issue by douglasg14b** [talonhub/community#783]
It doesn't look like negative numbers are parsed out when said. Talon seems to reliably recognize the word `negative`. The word `minus` works already, and I see `negative` defined beside it, but it doesn't appear to work?

Such as `negative 5`, `negative 78` ...etc

 I was scanning through numbers.py,  but I honestly don't quite understand the talon API enough understand what needs to be done to add that as a modifier.

**Comment by splondike** [comment]
'minus <number>'  is actually two different commands chained together. `minus` is the first command (the symbol_key capture in `misc/keys.talon`) and the number part is the second one (registered in `text/numbers.talon`). The number_signed capture that you were referring to isn't actually used anywhere in the repo I think.

I think I be in favor of your proposition to change the command in `text/numbers.talon` to use number_signed.

**Comment by AndreasArvidsson** [comment]
You can now in community say `"numb negative 5"` or `"numb minus 5"`
https://github.com/talonhub/community/blob/f27cb0192cedfe25468aa68f175cbc8b84db3f6c/core/numbers/numbers.py#L252
