### ISSUE TITLE
Snippets that work anywhere

### ISSUE THREAD

**Issue by pokey** [talonhub/community#848]
@AndreasArvidsson has a snippet system that falls back to text insertion in contexts that don't have proper snippet support. It even calculates the number of arrow key steps it has to take to get to the default tab stop. 
https://github.com/AndreasArvidsson/andreas-talon/blob/ec039ba885e41c59943a722a05883e8d9460ea68/text/snippets.py#L15

_Originally posted by @AndreasArvidsson in https://github.com/knausj85/knausj_talon/pull/830#discussion_r867513112_

**Comment by AndreasArvidsson** [comment]
I have made further work on my snippet representation
https://github.com/AndreasArvidsson/andreas-talon/blob/master/core/snippets/README.md

The idea is to have a single snippet format Talon side that you can use either with your editor or just as plaintext. I have been running with the above implementation for a short while and it appears to be working. My plan is to add this to community, but I think we may need to have a discussion about it first?
@rntz @nriley @pokey @knausj85 @phillco

**Comment by knausj85** [comment]
This looks awesome, I think we should definitely bring this in.

**Comment by AndreasArvidsson** [comment]
@knausj85 I will make a pr!

**Comment by knausj85** [comment]
I'd be inclined to kill the old snippet implementation, as it's disabled by default anyway.

Your implementation + cursorless snippets is better IMO
