### ISSUE TITLE
Move language modes to CSV

### ISSUE THREAD

**Issue by wenkokke** [talonhub/community#895]
There’s a longstanding comment in `code/code.py` about moving the definition of language modes to a CSV file:
https://github.com/knausj85/knausj_talon/blob/b0248921be6b47d33d68c368f6676aa4e5d929ef/code/code.py#L6-L9

My Talon user directory has had language modes in a CSV file for a while now.

- [talon-user/core/language_mode/language_mode.py](https://github.com/wenkokke/talon-user/blob/814a0ef5426ee8f8ac5e99737212b7f1591431ba/core/language_mode/language_mode.py)
- [talon-user/settings/language_modes.csv](https://github.com/wenkokke/talon-user/blob/dev/settings/language_modes.csv)

Would there be any interest in copying this over?

**Comment by knausj85** [comment]
Closing in favor of https://github.com/talonhub/community/issues/1585
