### ISSUE TITLE
Possibly convert to organization to allow for additional repo administrators

### ISSUE THREAD

**Issue by phillco** [talonhub/community#935]
One thing that came up in the rush to fix #922 is that some maintainers like @rntz no longer have the ability to push directly to `main`, because of the new branch protection rules which were checked in to enforce formatting. While pushing directly to main should be rare, this ability can be handy in emergencies when broken code gets checked in.

As I understand it, there is a setting in branch protection rules to allow repository administrators to bypass any protection rule. But as [knausj_talon](https://github.com/knausj85/knausj_talon) is a personal repository, you can't add additional administrators, just collaborators with write access -- the owner is the only administrator.

However, if we moved to a (free) GitHub organization, we could add additional administrators on the repository, while still maintaining @knausj85 as the ultimate owner. Basically:

* We would create a new organization with @knausj85 as the "owner" (presuming they don't want to convert their personal account to an organization, which looks to be pretty heavy handed)
* We would transfer https://github.com/knausj85/knausj_talon to the new organization. GitHub should seamlessly preserve redirects under the old name so this won't require any users to update anything [1]
* Select maintainers would be added as administrators on knausj_talon.

As a bonus, this will also allow those administrators to adjust repository settings as needed without needing @knausj85 to do it. This again should be rare, but might be nice to have.

[1] My understanding is they will preserve the old rename indefinitely unless somebody were to make a new https://github.com/knausj85/knausj_talon. Although when you fetch with the old name they will suggest that you update to the new one. Note that this is distinct from their branch renaming support, which does require user action.

**Comment by knausj85** [comment]
This is a good idea. 

I wonder if it makes sense to transfer to the existing [TalonCommunity](https://github.com/TalonCommunity). Any thoughts, @2shea?

**Comment by rntz** [comment]
Bumping this. @2shea, are you happy to have knausj_talon be transferred to TalonCommunity?

**Comment by rntz** [comment]
@phillco if this were owned by TalonCommunity, how would that effect who had admin/push access to the repo?

**Comment by phillco** [comment]
Basically, the owners of the organization would have full admin access do
everything in the organization, and they can choose to make others
repository admins.

I believe those who have write access (the existing maintainers) would keep
it by default.

**Comment by rntz** [comment]
Looks like the owners of TalonCommunity are 2shea, myself, and aegis/lunixbochs/Ryan. I'm sure we could add knausj to that list if he wants, too.

I'd like to get confirmation from @lunixbochs that he thinks transferring knausj_talon to TalonCommunity is a good idea / if there are any security concerns here. If he has no objections I'd be in favor of doing it.

**Comment by knausj85** [comment]
@rntz / @lunixbochs - I'm happy to move this over to Talon Community if that's the consensus. 

It looks like I need privileges within Talon Community sufficient to create a repo to do so?

My only ask is to remain an admin on the repo.

**Comment by rntz** [comment]
@lunixbochs says on Slack that his main question at this point is naming, of both the organization and the repo. Since this org & repo are likely to be around for a while, it would be good if they were named things that are both short to type (since our users have hand pain) and easy to speak (for obvious reasons).

While renaming an organization does leave redirects, anyone else can later come along and create an org with the previous name, usurping those redirects. That's a potential security hazard (you pull from knausj and suddenly you're pulling from a malicious repo), so we'd also like to minimize the # of renames we have to do here.

`TalonCommunity/knausj_talon` is both long and hard to speak. @lunixbochs suggests maybe `TalonUsers/common`. Other ideas?

**Comment by knausj85** [comment]
I think it's time for a vote to get this done.

Some ChatGPT-inspired ideas follow...

Organization Name
- TalonUser 🚀
- SpeechKit 👍
- VoiceLibrary 👀
- TalonLibrary ❤️

Repo name:
- community 🎉
- common 😄

😕=other ideas

**Comment by lunixbochs** [comment]
https://github.com/talonhub /communityOn May 29, 2023, at 1:01 PM, Jeff Knaus ***@***.***> wrote:﻿
I think it's time for a vote to get this done.
Some ChatGPT-inspired ideas follow...
Organization Name

TalonUser 🚀
SpeechKit 👍
VoiceLibrary 👀
TalonLibrary ❤️

Repo name:

community 🎉
common 😄

😕=other ideas

**Comment by 2shea** [comment]
Sorry I missed this conversation! My past self set up some unfortunate email filters and I'm just now seeing this.
