### ISSUE TITLE
Cleaner commands with a single ctrl/cmd-key action

### ISSUE THREAD

**Issue by auscompgeek** [talonhub/community#942]
During this week's grooming session it was brought up that the majority of the Python actions are only defined to allow for macOS support with the same `.talon` file, and most cross-platform apps only differ in their keyboard shortcuts by usage of <kbd>cmd</kbd> or <kbd>ctrl</kbd>.

We could probably delete a large chunk of code, and easily migrate a bunch of the platform-specific `.talon` files, by having a single action to press a key with <kbd>cmd</kbd> or <kbd>ctrl</kbd>.

Funnily enough, we actually have one already, added along with Thunderbird support in #892:

https://github.com/knausj85/knausj_talon/blob/bfb282178d78880fad6b69b76f7dd097208f1f65/apps/thunderbird/thunderbird.py#L84-L85

https://github.com/knausj85/knausj_talon/blob/bfb282178d78880fad6b69b76f7dd097208f1f65/apps/thunderbird/mac.py#L30-L31

The parameter name `keys` seems to be a misnomer and should probably be renamed to singular `key` to avoid confusion.

**Comment by auscompgeek** [comment]
Fair enough. To me `keys` implies it will modify all keys that are passed in, which is not the case. Perhaps for a more generic action that might actually be something we want? :shrug:

**Comment by auscompgeek** [comment]
Looks like we have a similar action for Chrome now too (added in #1014), but it's actually wrong - see #446.

**Comment by knausj85** [comment]
It's preferable not to do this to support VMs and such.

See https://github.com/talonhub/community/issues/446

Closing.
