### ISSUE TITLE
Rename `"phones <homophone>"` command

### ISSUE THREAD

**Issue by pokey** [talonhub/community#987]
This command is here:

https://github.com/knausj85/knausj_talon/blob/4977499c7be81a6b5da7d100dc14d97969883330/text/homophones.talon#L1

It allows saying eg "phones red", which will pop up a dialogue containing eg "read", "red", etc.  This command conflicts with the cursorless "phones" command to cycle through homophones on a target.

This conflict tends to bite Cursorless users a lot, and I wonder how many people are actually using this knausj phones command.  Maybe we could at least remap it to "phones show <homophone>"?

**Comment by nriley** [comment]
For current users of this command, would it be alright if we added a word after 'phones', such as 'phones for', or 'phones of'?

**Comment by erhoppe** [comment]
How about "phones list <word>"? I feel like that's less like to get slurred together without being too difficult to say. I'd be fine with adding that as an occasional user of "phones <word>" personally.

**Comment by reidma** [comment]
If you were to eliminate the knausj version of the "phones" command, then I believe there would be no homophone correction functionality outside of Cursorless, which would probably be a problem for the majority of talon users. I would vote for renaming one of the commands.

**Comment by pokey** [comment]
No we're just proposing to change / remove that single line. All the other commands in https://github.com/knausj85/knausj_talon/blob/main/core/homophones/homophones.talon would stay the same

But I think just renaming the command is better than removing it anyway

**Comment by rntz** [comment]
VOTING TIME (vote for all options you approve of)

🎉  "phones for"
🚀  "phones list"
👀 "phones of"
❤️ "phones show"

**Comment by AndreasArvidsson** [comment]
https://github.com/talonhub/community/pull/1170#issuecomment-2466311297
